// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NonProfitDB_Wilkinson.Models;

public partial class BankAccount
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string BankName { get; set; }

    public string AccountNumber { get; set; }

    public double? CurrentBalance { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual ICollection<TransactionLedger> TransactionLedgers { get; set; } = new List<TransactionLedger>();
}