// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NonProfitDB_Wilkinson.Models;

public partial class Donation
{
    public int DonationId { get; set; }

    public int DonorId { get; set; } //F key

    public int? DonationCategoryId { get; set; }

    public DateOnly DonationDate { get; set; }

    public DateTime EntryDate { get; set; }

    public double Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string ReferenceNumber { get; set; }

    public string Notes { get; set; }

    public string RecordedBy { get; set; }

    public virtual DonationCategory DonationCategory { get; set; }

    public virtual Donor Donor { get; set; }
}