// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NonProfitDB_Wilkinson.Models;

public partial class DonationCategory
{
    public int DonationCategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Donation> Donations { get; set; } = new List<Donation>();
}