// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NonProfitDB_Wilkinson.Models;

public partial class Expense
{
    public int ExpenseId { get; set; }

    public int ExpenseCategoryId { get; set; }

    public DateOnly ExpenseDate { get; set; }

    public DateTime EntryDate { get; set; }

    public double Amount { get; set; }

    public string Payee { get; set; }

    public string PaymentMethod { get; set; }

    public string ReferenceNumber { get; set; }

    public string Notes { get; set; }

    public string RecordedBy { get; set; }

    public virtual ExpenseCategory ExpenseCategory { get; set; }
}