// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NonProfitDB_Wilkinson.Models;

public partial class TransactionLedger
{
    public int TransactionId { get; set; }

    public string TransactionType { get; set; }

    public int ReferenceId { get; set; }

    public DateOnly TransactionDate { get; set; }

    public DateTime EntryDate { get; set; }

    public double Amount { get; set; }

    public int? AccountId { get; set; }

    public double? BalanceAfter { get; set; }

    public string Notes { get; set; }

    public virtual BankAccount Account { get; set; }
}